### ISSUE TITLE
Error Gazebo Plugin Schunk SVH 5 Finger Hand

### ISSUE THREAD

**Issue by HJKIMRobotics** [fzi-forschungszentrum-informatik/schunk_svh_ros_driver#17]
Hi. I'm just wondering the error when I plugin SVH 5 Finger hand into Gazebo environment.

First, I attached the hand to my arm and tried to build in MoveIt environment. In Rviz, it was confirmed that all TF and TF pose, which are related to the hand and arm came out properly. However, the pose of the hand is extremely unnatural in Gazebo environment at the same time, and also the fingers continue to shake in real-time as shown in the figure below. Even, a couple of fingers fall off when the arm was moved. I'm sorry for that I think this picture cannot illustrate my problem perfectly, but I hope you can understand it well.

![hand_problem](https://user-images.githubusercontent.com/86734698/205929795-702cce76-de74-4119-87a3-fd34cb568098.gif)

I though my URDF file that I made it was strange, so I tried to plug only schunk svh hand into Gazebo using the original schunk_svh_ros_driver provided by Schunk. As a result, it bounded hugely like a basketball, not a fixed on the floor. Likewise, the fingers kept swinging.

What I'm curious about is that Rviz environment was worked well, but Gazebo environment did not work well.
May I ask you why this problem happens and what I'm missing?

Thank you.

**Comment by stefanscherzinger** [comment]
Thanks @HJKIMRobotics for reporting this.

I'll try to reproduce this in a simple setup and report back. At first sight, it looks like the joints are loaded without actuation (no dedicated controller), which could explain their free oscillation. Can you move the individual joints via the `rqt_joint_trajectory_controller`?

**Comment by HJKIMRobotics** [comment]
@stefanscherzinger 
Thank you so much for explaining my issue in detail. I will try this, and also I will let you know as soon as possible.

**Comment by HJKIMRobotics** [comment]
@stefanscherzinger 

I can confirm that everything works great!!! 
Thank you so much for your quick response and providing the gazebo example.

Have a good day.

Kind regards
HJ Kim

**Comment by stefanscherzinger** [comment]
You are welcome!
